'use strict'

process.env.NODE_ENV = 'development'

const WebpackDevServer = require('webpack-dev-server')
const chalk = require('chalk')
const config = require('../config/webpack.config.dev')
const Webpack = require('webpack')
const devServerConfig = require('../config/webpack-dev-server.config')

// Tools like Cloud9 rely on this.
const DEFAULT_PORT = parseInt(process.env.PORT, 10) || 3000
const compiler = new Webpack(config)

function run (port) {
  const protocol = process.env.HTTPS === 'true' ? 'https' : 'http'
  const host = process.env.HOST || 'localhost'

  // Serve webpack assets generated by the compiler over a web sever.
  const devServer = new WebpackDevServer(compiler, devServerConfig)

  // Launch WebpackDevServer.
  devServer.listen(port, err => {
    if (err) {
      return console.log(err)
    }

    console.log(chalk.cyan(`Starting the development server on ${protocol}://${host}:${port}/...`))
    console.log()
  })
}

run(DEFAULT_PORT)
